# Production-only configuration for subdirectory deployment
# This file is merged with config.toml during CI/CD builds

[module]
  [[module.mounts]]
    source = "themes/hugo-geekdoc/static"
    target = "static"
  [[module.mounts]]
    source = "static"
    target = "static"