name: Link Checker

on:
  schedule:
    # Run on the 1st of every month at 9 AM UTC
    - cron: '0 9 1 * *'
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          # Configuration file specifies what to check and exclude
          args: --verbose --no-progress --config '.lycherc.toml' '.'
          # Fail action on broken links
          fail: true
          # Output results to a file for the issue creation step
          output: lychee-report.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let reportContent = '';

            try {
              reportContent = fs.readFileSync('lychee-report.md', 'utf8');
            } catch (error) {
              reportContent = 'Report file not found. See workflow logs for details.';
            }

            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔗 Monthly Link Check Failed',
              body: `The monthly link checker found broken links in the documentation.

## Workflow Run
[View full workflow run details](${context.payload.repository.html_url}/actions/runs/${context.runId})

## Link Check Report
${reportContent}

---
_This issue was automatically created by the link checker workflow on ${new Date().toISOString().split('T')[0]}_`,
              labels: ['documentation', 'broken-links']
            });
            console.log('Created issue:', issue.data.number);
