name: Vale Linting

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.txt'
      - '.vale.ini'
      - 'styles/**'

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vale
        uses: errata-ai/vale-action@v2
        with:
          files: all
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}