name: Vale Linting

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.txt'
      - '.vale.ini'
      - 'styles/**'

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vale
        run: |
          wget -qO- https://github.com/errata-ai/vale/releases/download/v3.12.0/vale_3.12.0_Linux_64-bit.tar.gz | tar -xzf - -C /usr/local/bin vale
          chmod +x /usr/local/bin/vale
          vale --version

      - name: Debug styles directory
        run: |
          echo "Contents of styles directory:"
          ls -la styles/
          echo "Contents of TrueNAS directory:"
          ls -la styles/TrueNAS/
          echo "TrueNAS meta.json:"
          cat styles/TrueNAS/meta.json

      - name: Run Vale
        run: |
          vale sync
          vale content/